name: Deploy

on: 
  workflow_dispatch:
    inputs:
     environment:
      type: environment
      description: Select the environment
     dryRun:
      type: boolean
      description: Dry run
    
    
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  deploy:
    name: Deploy
    needs: [build]
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Upload files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{secrets.DEPLOY_FTP_SERVER}}
        username: ${{secrets.DEPLOY_FTP_USER}}
        password: ${{secrets.DEPLOY_FTP_PASSWORD}}
        local-dir: ./build/
        server-dir: ${{vars.DEPLOY_FTP_SERVER_DIR}}
        dry-run: ${{inputs.dryRun}}
